@echo off
REM ============================================
REM nDNA Image Download Script for Windows
REM Run this from inside docs\images\
REM Requires: curl (built into Windows 10+)
REM ============================================

curl -L -o "Africa_Asia_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Africa_Asia_drift.gif"
curl -L -o "Africa_China_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Africa_China_drift.gif"
curl -L -o "Africa_LatinAmerica_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Africa_LatinAmerica_drift.gif"
curl -L -o "Africa_MiddleEast_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Africa_MiddleEast_drift.gif"
curl -L -o "Asia_China_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Asia_China_drift.gif"
curl -L -o "Asia_LatinAmerica_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Asia_LatinAmerica_drift.gif"
curl -L -o "Asia_MiddleEast_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Asia_MiddleEast_drift.gif"
curl -L -o "Australia_Africa_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Australia_Africa_drift.gif"
curl -L -o "Australia_Asia_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Australia_Asia_drift.gif"
curl -L -o "Australia_China_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Australia_China_drift.gif"
curl -L -o "Australia_LatinAmerica_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Australia_LatinAmerica_drift.gif"
curl -L -o "Australia_MiddleEast_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Australia_MiddleEast_drift.gif"
curl -L -o "China_LatinAmerica_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/China_LatinAmerica_drift.gif"
curl -L -o "China_MiddleEast_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/China_MiddleEast_drift.gif"
curl -L -o "Europe_Africa_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Europe_Africa_drift.gif"
curl -L -o "Europe_Asia_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Europe_Asia_drift.gif"
curl -L -o "Europe_Australia_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Europe_Australia_drift.gif"
curl -L -o "Europe_China_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Europe_China_drift.gif"
curl -L -o "Europe_LatinAmerica_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Europe_LatinAmerica_drift.gif"
curl -L -o "Europe_MiddleEast_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Europe_MiddleEast_drift.gif"
curl -L -o "Europe_NorthAmerica_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/Europe_NorthAmerica_drift.gif"
curl -L -o "Final_thermodynamic_length.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/Final_thermodynamic_length.gif"
curl -L -o "MiddleEast_LatinAmerica_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/MiddleEast_LatinAmerica_drift.gif"
curl -L -o "NorthAmerica_Africa_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/NorthAmerica_Africa_drift.gif"
curl -L -o "NorthAmerica_Asia_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/NorthAmerica_Asia_drift.gif"
curl -L -o "NorthAmerica_Australia_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/NorthAmerica_Australia_drift.gif"
curl -L -o "NorthAmerica_China_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/NorthAmerica_China_drift.gif"
curl -L -o "NorthAmerica_LatinAmerica_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/NorthAmerica_LatinAmerica_drift.gif"
curl -L -o "NorthAmerica_MiddleEast_drift.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/aether_drift_fusions/NorthAmerica_MiddleEast_drift.gif"
curl -L -o "africa_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/africa_dpo_rotation.gif"
curl -L -o "africa_ndna_final.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/africa_ndna_final.gif"
curl -L -o "all.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/15_llms/all.gif"
curl -L -o "asia_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/asia_dpo_rotation.gif"
curl -L -o "asia_ndna_collapse.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/asia_ndna_collapse.gif"
curl -L -o "australia_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/australia_dpo_rotation.gif"
curl -L -o "belief_vector_field.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/belief_vector_field.gif"
curl -L -o "belief_vector_field_side_by_side_refined.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/belief_vector_field_side_by_side_refined.gif"
curl -L -o "belief_vector_flow.png" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/semantic_hydrodynamics/belief_vector_flow.png"
curl -L -o "china_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/china_dpo_rotation.gif"
curl -L -o "china_ndna_final.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/china_ndna_final.gif"
curl -L -o "corpus_creation_and_refinement.png" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/images/corpus_creation_and_refinement.png"
curl -L -o "deepseek.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/15_llms/deepseek.gif"
curl -L -o "europe_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/europe_dpo_rotation.gif"
curl -L -o "europe_ndna_collapse_FINAL.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/europe_ndna_collapse_FINAL.gif"
curl -L -o "flow-simulation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/semantic_hydrodynamics/flow-simulation.gif"
curl -L -o "gemma.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/15_llms/gemma.gif"
curl -L -o "king_queen.png" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/images/king_queen.png"
curl -L -o "laminar_flow.png" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/semantic_hydrodynamics/laminar_flow.png"
curl -L -o "latinamerica.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/latinamerica.gif"
curl -L -o "latinamerica_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/latinamerica_dpo_rotation.gif"
curl -L -o "llama.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/15_llms/llama.gif"
curl -L -o "llama_Africa_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_Africa_rotation.gif"
curl -L -o "llama_Asia_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_Asia_rotation.gif"
curl -L -o "llama_Australia_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_Australia_rotation.gif"
curl -L -o "llama_China_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_China_rotation.gif"
curl -L -o "llama_Europe_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_Europe_rotation.gif"
curl -L -o "llama_LatinAmerica_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_LatinAmerica_rotation.gif"
curl -L -o "llama_MiddleEast_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_MiddleEast_rotation.gif"
curl -L -o "llama_NorthAmerica_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_NorthAmerica_rotation.gif"
curl -L -o "llama_collapse_v2_1.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/llama_collapse_v2_1.gif"
curl -L -o "llama_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/llama_dpo_rotation.gif"
curl -L -o "llama_vs_cultures_group_tagged_360.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/cultural_ndna/llama_vs_cultures_group_tagged_360.gif"
curl -L -o "llama_vs_cultures_offspring_students.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/llama_vs_cultures_offspring_students.gif"
curl -L -o "llama_vs_cultures_with_offsprings_360.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/llama_vs_cultures_with_offsprings_360.gif"
curl -L -o "middleeast_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/middleeast_dpo_rotation.gif"
curl -L -o "middleeast_ndna_final.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/middleeast_ndna_final.gif"
curl -L -o "mistral.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/15_llms/mistral.gif"
curl -L -o "nDNA_LLaMA2_NeoX_Offspring.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/aether/nDNA_LLaMA2_NeoX_Offspring.gif"
curl -L -o "ndna_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/ndna_dpo_rotation.gif"
curl -L -o "ndna_llama_commonsense_axes_match.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/task_nDNA/ndna_llama_commonsense_axes_match.gif"
curl -L -o "ndna_llama_dialogue_axes_match.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/task_nDNA/ndna_llama_dialogue_axes_match.gif"
curl -L -o "ndna_llama_qa_axes_match.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/task_nDNA/ndna_llama_qa_axes_match.gif"
curl -L -o "ndna_llama_reasoning_axes_match.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/task_nDNA/ndna_llama_reasoning_axes_match.gif"
curl -L -o "ndna_llama_summarization_axes_match.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/task_nDNA/ndna_llama_summarization_axes_match.gif"
curl -L -o "ndna_refined_story.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/ndna_refined_story.gif"
curl -L -o "northamerica_dpo_rotation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/collapse/northamerica_dpo_rotation.gif"
curl -L -o "northamerica_ndna_collapse_FINAL.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/alignment/northamerica_ndna_collapse_FINAL.gif"
curl -L -o "others.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/15_llms/others.gif"
curl -L -o "pipe.jpg" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/semantic_hydrodynamics/pipe.jpg"
curl -L -o "qwen.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/gifs/15_llms/qwen.gif"
curl -L -o "spectral_curvature.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/spectral_curvature.gif"
curl -L -o "spectral_curvature_llama_ndna_animation.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/spectral_curvature_llama_ndna_animation.gif"
curl -L -o "spectral_flow.png" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/semantic_hydrodynamics/spectral_flow.png"
curl -L -o "thermodynamic_length.gif" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/thermodynamic_length.gif"
curl -L -o "thermodynamics_flow.png" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/semantic_hydrodynamics/thermodynamics_flow.png"
curl -L -o "universal_dna.png" "https://cdn.jsdelivr.net/gh/pragyaai/cdn-assets/assets/ndna/task_nDNA/universal_dna.png"

echo.
echo Download complete! 86 files downloaded.
echo NOTE: 5 files need manual download (see below)
echo   MANUAL: aether.png (from model-merging page _files folder)
echo   MANUAL: dpo_steering_vector_field.png (from alignment page _files folder)
echo   MANUAL: logit_geometry_vector_projection.png (from alignment page _files folder)
echo   MANUAL: mechanistic.png (from alignment page _files folder)
echo   MANUAL: steering_vector_3d_directions.png (from alignment page _files folder)